source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#inhibit_all_warnings!

target 'umeiTime' do
  
  use_frameworks!
  # Pods for umeiTime

  pod 'Moya'
  pod 'R.swift'
  pod 'ESPullToRefresh'
# version for Swift 4.1
  pod 'HandyJSON', '4.1.3'
  pod 'Kingfisher', '4.9.0'
  pod 'ESTabBarController-swift', '2.6.2'
  pod 'Closures', '0.4'
  
end
